/**
 * Unit tests for Azure DevOps PR Review handlers
 * Tests review result parsing and finding transformations
 */
import { describe, it, expect } from 'vitest';

// Test types matching the handler's internal types
interface PRReviewFinding {
  id: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  category: string;
  title: string;
  description: string;
  file: string;
  line: number;
  endLine?: number;
  suggestedFix?: string;
  fixable: boolean;
}

interface PRReviewResult {
  prId: number;
  project: string;
  success: boolean;
  findings: PRReviewFinding[];
  summary: string;
  overallStatus: 'approve' | 'request_changes' | 'comment';
  reviewedAt: string;
  reviewedCommitSha?: string;
  isFollowupReview: boolean;
  previousReviewId?: number;
  resolvedFindings: string[];
  unresolvedFindings: string[];
  newFindingsSinceLastReview: string[];
  hasPostedFindings: boolean;
  postedFindingIds: string[];
}

interface RawReviewData {
  pr_id: number;
  project: string;
  success: boolean;
  findings?: Array<{
    id: string;
    severity: string;
    category: string;
    title: string;
    description: string;
    file: string;
    line: number;
    end_line?: number;
    suggested_fix?: string;
    fixable?: boolean;
  }>;
  summary?: string;
  overall_status?: string;
  reviewed_at?: string;
  reviewed_commit_sha?: string;
  is_followup_review?: boolean;
  previous_review_id?: number;
  resolved_findings?: string[];
  unresolved_findings?: string[];
  new_findings_since_last_review?: string[];
  has_posted_findings?: boolean;
  posted_finding_ids?: string[];
}

/**
 * Parse raw review data from JSON file into PRReviewResult
 */
function parseReviewResult(data: RawReviewData): PRReviewResult {
  return {
    prId: data.pr_id,
    project: data.project,
    success: data.success,
    findings: data.findings?.map((f) => ({
      id: f.id,
      severity: f.severity as PRReviewFinding['severity'],
      category: f.category,
      title: f.title,
      description: f.description,
      file: f.file,
      line: f.line,
      endLine: f.end_line,
      suggestedFix: f.suggested_fix,
      fixable: f.fixable ?? false,
    })) ?? [],
    summary: data.summary ?? '',
    overallStatus: (data.overall_status as PRReviewResult['overallStatus']) ?? 'comment',
    reviewedAt: data.reviewed_at ?? new Date().toISOString(),
    reviewedCommitSha: data.reviewed_commit_sha,
    isFollowupReview: data.is_followup_review ?? false,
    previousReviewId: data.previous_review_id,
    resolvedFindings: data.resolved_findings ?? [],
    unresolvedFindings: data.unresolved_findings ?? [],
    newFindingsSinceLastReview: data.new_findings_since_last_review ?? [],
    hasPostedFindings: data.has_posted_findings ?? false,
    postedFindingIds: data.posted_finding_ids ?? [],
  };
}

/**
 * Format review body for posting as Azure DevOps thread comment
 */
function formatReviewBody(result: PRReviewResult, selectedFindingIds?: string[]): string {
  const selectedSet = selectedFindingIds ? new Set(selectedFindingIds) : null;
  const findings = selectedSet
    ? result.findings.filter(f => selectedSet.has(f.id))
    : result.findings;

  let body = `## Tarkeeba PR Review\n\n${result.summary}\n\n`;

  if (findings.length > 0) {
    const countText = selectedSet
      ? `${findings.length} selected of ${result.findings.length} total`
      : `${findings.length} total`;
    body += `### Findings (${countText})\n\n`;

    for (const f of findings) {
      const emoji = { critical: '🔴', high: '🟠', medium: '🟡', low: '🔵' }[f.severity] || '⚪';
      body += `#### ${emoji} [${f.severity.toUpperCase()}] ${f.title}\n`;
      body += `📁 \`${f.file}:${f.line}\`\n\n`;
      body += `${f.description}\n\n`;
      const suggestedFix = f.suggestedFix?.trim();
      if (suggestedFix) {
        body += `**Suggested fix:**\n\`\`\`\n${suggestedFix}\n\`\`\`\n\n`;
      }
    }
  } else {
    body += `*No findings selected for this review.*\n\n`;
  }

  body += `---\n*This review was generated by Tarkeeba.*`;

  return body;
}

/**
 * Calculate severity score for sorting
 */
function getSeverityScore(severity: string): number {
  const scores = { critical: 4, high: 3, medium: 2, low: 1 };
  return scores[severity as keyof typeof scores] ?? 0;
}

describe('Azure DevOps PR Review Handlers', () => {
  describe('parseReviewResult', () => {
    const baseRawData: RawReviewData = {
      pr_id: 42,
      project: 'test/project',
      success: true,
      findings: [
        {
          id: 'finding-abc123',
          severity: 'high',
          category: 'security',
          title: 'SQL Injection Vulnerability',
          description: 'User input is directly concatenated into SQL query',
          file: 'src/db.ts',
          line: 42,
          end_line: 45,
          suggested_fix: 'Use parameterized queries',
          fixable: true
        }
      ],
      summary: 'Found 1 high severity issue',
      overall_status: 'request_changes',
      reviewed_at: '2024-01-15T10:00:00Z',
      reviewed_commit_sha: 'abc123def456',
      is_followup_review: false,
      resolved_findings: [],
      unresolved_findings: [],
      new_findings_since_last_review: [],
      has_posted_findings: false,
      posted_finding_ids: []
    };

    it('should parse basic review result correctly', () => {
      const result = parseReviewResult(baseRawData);

      expect(result.prId).toBe(42);
      expect(result.project).toBe('test/project');
      expect(result.success).toBe(true);
      expect(result.summary).toBe('Found 1 high severity issue');
      expect(result.overallStatus).toBe('request_changes');
    });

    it('should parse findings correctly', () => {
      const result = parseReviewResult(baseRawData);

      expect(result.findings).toHaveLength(1);
      expect(result.findings[0].id).toBe('finding-abc123');
      expect(result.findings[0].severity).toBe('high');
      expect(result.findings[0].category).toBe('security');
      expect(result.findings[0].title).toBe('SQL Injection Vulnerability');
      expect(result.findings[0].file).toBe('src/db.ts');
      expect(result.findings[0].line).toBe(42);
      expect(result.findings[0].endLine).toBe(45);
      expect(result.findings[0].suggestedFix).toBe('Use parameterized queries');
      expect(result.findings[0].fixable).toBe(true);
    });

    it('should parse commit SHA and timestamps', () => {
      const result = parseReviewResult(baseRawData);

      expect(result.reviewedAt).toBe('2024-01-15T10:00:00Z');
      expect(result.reviewedCommitSha).toBe('abc123def456');
    });

    it('should parse followup review metadata', () => {
      const followupData: RawReviewData = {
        ...baseRawData,
        is_followup_review: true,
        previous_review_id: 100,
        resolved_findings: ['finding-abc123'],
        unresolved_findings: ['finding-xyz789'],
        new_findings_since_last_review: ['finding-new001']
      };

      const result = parseReviewResult(followupData);

      expect(result.isFollowupReview).toBe(true);
      expect(result.previousReviewId).toBe(100);
      expect(result.resolvedFindings).toEqual(['finding-abc123']);
      expect(result.unresolvedFindings).toEqual(['finding-xyz789']);
      expect(result.newFindingsSinceLastReview).toEqual(['finding-new001']);
    });

    it('should parse posted findings', () => {
      const postedData: RawReviewData = {
        ...baseRawData,
        has_posted_findings: true,
        posted_finding_ids: ['finding-abc123', 'finding-xyz789']
      };

      const result = parseReviewResult(postedData);

      expect(result.hasPostedFindings).toBe(true);
      expect(result.postedFindingIds).toEqual(['finding-abc123', 'finding-xyz789']);
    });

    it('should handle missing optional fields with defaults', () => {
      const minimalData: RawReviewData = {
        pr_id: 1,
        project: 'test',
        success: true
      };

      const result = parseReviewResult(minimalData);

      expect(result.prId).toBe(1);
      expect(result.findings).toEqual([]);
      expect(result.summary).toBe('');
      expect(result.overallStatus).toBe('comment');
      expect(result.isFollowupReview).toBe(false);
      expect(result.resolvedFindings).toEqual([]);
      expect(result.hasPostedFindings).toBe(false);
      expect(result.reviewedAt).toBeTruthy(); // Should have current timestamp
    });

    it('should parse multiple findings', () => {
      const multipleFindings: RawReviewData = {
        ...baseRawData,
        findings: [
          { id: 'f1', severity: 'critical', category: 'security', title: 'Critical', description: 'desc', file: 'a.ts', line: 1, fixable: false },
          { id: 'f2', severity: 'high', category: 'quality', title: 'High', description: 'desc', file: 'b.ts', line: 2, fixable: true },
          { id: 'f3', severity: 'low', category: 'style', title: 'Low', description: 'desc', file: 'c.ts', line: 3, fixable: false }
        ]
      };

      const result = parseReviewResult(multipleFindings);

      expect(result.findings).toHaveLength(3);
      expect(result.findings[0].severity).toBe('critical');
      expect(result.findings[1].severity).toBe('high');
      expect(result.findings[2].severity).toBe('low');
    });

    it('should handle findings with missing optional properties', () => {
      const minimalFinding: RawReviewData = {
        pr_id: 1,
        project: 'test',
        success: true,
        findings: [
          { id: 'f1', severity: 'high', category: 'security', title: 'Issue', description: 'desc', file: 'file.ts', line: 10 }
        ]
      };

      const result = parseReviewResult(minimalFinding);

      expect(result.findings[0].endLine).toBeUndefined();
      expect(result.findings[0].suggestedFix).toBeUndefined();
      expect(result.findings[0].fixable).toBe(false);
    });
  });

  describe('formatReviewBody', () => {
    const baseResult: PRReviewResult = {
      prId: 42,
      project: 'test/project',
      success: true,
      findings: [
        {
          id: 'f1',
          severity: 'critical',
          category: 'security',
          title: 'SQL Injection',
          description: 'Concatenating user input into SQL',
          file: 'src/db.ts',
          line: 42,
          suggestedFix: 'Use parameterized queries',
          fixable: true
        },
        {
          id: 'f2',
          severity: 'low',
          category: 'style',
          title: 'Missing semicolon',
          description: 'JavaScript style issue',
          file: 'src/app.ts',
          line: 100,
          fixable: true
        }
      ],
      summary: 'Found 2 issues',
      overallStatus: 'request_changes',
      reviewedAt: '2024-01-15T10:00:00Z',
      isFollowupReview: false,
      resolvedFindings: [],
      unresolvedFindings: [],
      newFindingsSinceLastReview: [],
      hasPostedFindings: false,
      postedFindingIds: []
    };

    it('should format review body with all findings', () => {
      const body = formatReviewBody(baseResult);

      expect(body).toContain('Tarkeeba PR Review');
      expect(body).toContain('Found 2 issues');
      expect(body).toContain('SQL Injection');
      expect(body).toContain('Missing semicolon');
      expect(body).toContain('src/db.ts:42');
      expect(body).toContain('src/app.ts:100');
    });

    it('should include severity emojis', () => {
      const body = formatReviewBody(baseResult);

      expect(body).toContain('🔴'); // critical
      expect(body).toContain('🔵'); // low
      expect(body).toContain('[CRITICAL]');
      expect(body).toContain('[LOW]');
    });

    it('should include suggested fixes when available', () => {
      const body = formatReviewBody(baseResult);

      expect(body).toContain('**Suggested fix:**');
      expect(body).toContain('Use parameterized queries');
    });

    it('should format selected findings only', () => {
      const body = formatReviewBody(baseResult, ['f2']);

      expect(body).toContain('1 selected of 2 total');
      expect(body).toContain('Missing semicolon');
      expect(body).not.toContain('SQL Injection');
    });

    it('should handle empty findings list', () => {
      const emptyResult: PRReviewResult = {
        ...baseResult,
        findings: []
      };

      const body = formatReviewBody(emptyResult);

      expect(body).toContain('*No findings selected for this review.*');
      expect(body).not.toContain('###');
    });

    it('should handle findings without suggested fix', () => {
      const noFixResult: PRReviewResult = {
        ...baseResult,
        findings: [
          {
            ...baseResult.findings[0],
            suggestedFix: undefined
          }
        ]
      };

      const body = formatReviewBody(noFixResult);

      expect(body).not.toContain('**Suggested fix:**');
      expect(body).toContain('SQL Injection');
    });

    it('should include footer attribution', () => {
      const body = formatReviewBody(baseResult);

      expect(body).toContain('---');
      expect(body).toContain('*This review was generated by Tarkeeba.*');
    });

    it('should handle selected findings that do not exist', () => {
      const body = formatReviewBody(baseResult, ['f999']);

      expect(body).toContain('0 selected of 2 total');
      expect(body).toContain('*No findings selected for this review.*');
    });
  });

  describe('getSeverityScore', () => {
    it('should assign correct severity scores', () => {
      expect(getSeverityScore('critical')).toBe(4);
      expect(getSeverityScore('high')).toBe(3);
      expect(getSeverityScore('medium')).toBe(2);
      expect(getSeverityScore('low')).toBe(1);
    });

    it('should return 0 for unknown severity', () => {
      expect(getSeverityScore('unknown')).toBe(0);
      expect(getSeverityScore('')).toBe(0);
    });

    it('should allow sorting by severity', () => {
      const findings: PRReviewFinding[] = [
        { id: '1', severity: 'low', category: 'test', title: 't', description: 'd', file: 'f', line: 1, fixable: false },
        { id: '2', severity: 'critical', category: 'test', title: 't', description: 'd', file: 'f', line: 2, fixable: false },
        { id: '3', severity: 'medium', category: 'test', title: 't', description: 'd', file: 'f', line: 3, fixable: false }
      ];

      const sorted = [...findings].sort((a, b) => getSeverityScore(b.severity) - getSeverityScore(a.severity));

      expect(sorted[0].severity).toBe('critical');
      expect(sorted[1].severity).toBe('medium');
      expect(sorted[2].severity).toBe('low');
    });
  });

  describe('Overall status validation', () => {
    it('should represent approve status', () => {
      const result: PRReviewResult = {
        prId: 1,
        project: 'test',
        success: true,
        findings: [],
        summary: 'Looks good',
        overallStatus: 'approve',
        reviewedAt: '2024-01-15T10:00:00Z',
        isFollowupReview: false,
        resolvedFindings: [],
        unresolvedFindings: [],
        newFindingsSinceLastReview: [],
        hasPostedFindings: false,
        postedFindingIds: []
      };

      expect(result.overallStatus).toBe('approve');
    });

    it('should represent request_changes status', () => {
      const result: PRReviewResult = {
        prId: 1,
        project: 'test',
        success: true,
        findings: [
          { id: 'f1', severity: 'high', category: 'test', title: 't', description: 'd', file: 'f', line: 1, fixable: false }
        ],
        summary: 'Changes needed',
        overallStatus: 'request_changes',
        reviewedAt: '2024-01-15T10:00:00Z',
        isFollowupReview: false,
        resolvedFindings: [],
        unresolvedFindings: [],
        newFindingsSinceLastReview: [],
        hasPostedFindings: false,
        postedFindingIds: []
      };

      expect(result.overallStatus).toBe('request_changes');
    });

    it('should represent comment status', () => {
      const result: PRReviewResult = {
        prId: 1,
        project: 'test',
        success: true,
        findings: [
          { id: 'f1', severity: 'low', category: 'test', title: 't', description: 'd', file: 'f', line: 1, fixable: false }
        ],
        summary: 'Minor suggestions',
        overallStatus: 'comment',
        reviewedAt: '2024-01-15T10:00:00Z',
        isFollowupReview: false,
        resolvedFindings: [],
        unresolvedFindings: [],
        newFindingsSinceLastReview: [],
        hasPostedFindings: false,
        postedFindingIds: []
      };

      expect(result.overallStatus).toBe('comment');
    });
  });
});
